XX_VERSION_H="./xx_version.h"

clearAll() {
	rm -rf ${XX_VERSION_H}
}

gitRepoVersion() {
	XX_BRANCH="$(git name-rev --name-only --no-undefined HEAD)"
	XX_VERSION="$(git describe --abbrev=7 --dirty --always --tags)"
}

# For version output
versionOutput() {
	cat > "${XX_VERSION_H}" << EOF
/* Generated by ver.sh - DO NOT MODIFY IT! */
#ifndef XXVERSION_H
#define XXVERSION_H

#define XX_BRANCH 	    "${XX_BRANCH}"
#define XX_VERSION		"${XX_VERSION}"

#endif //XXVERSION_H

/* end */
EOF
}

clearAll
gitRepoVersion
versionOutput

